name: Python CI

on:
  push:
    branches:
      - master  # ou main, selon ta branche par défaut
  pull_request:
    branches:
      - master  # ou main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Version de Python que tu utilises

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run tests
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        export PYTHONPATH=.
        poetry run pytest
